/**
 * SECTIONS
 * 1. TEST CONNECTION
 */


// TEST CONNECTION
export const TEST_BACKEND_CONNECTION_START = 'TEST_BACKEND_CONNECTION_START';
export const TEST_BACKEND_CONNECTION_SUCCESS = 'TEST_BACKEND_CONNECTION_SUCCESS';
export const TEST_BACKEND_CONNECTION_FAILURE = 'TEST_BACKEND_CONNECTION_FAILURE';