/**
 * SECTIONS
 * 1. TEST CONNECTION
 */


// TEST CONNECTION
export const TEST_BACKEND_CONNECTION_START = 'TEST_BACKEND_CONNECTION_START';
export const TEST_BACKEND_CONNECTION_SUCCESS = 'TEST_BACKEND_CONNECTION_SUCCESS';
export const TEST_BACKEND_CONNECTION_FAILURE = 'TEST_BACKEND_CONNECTION_FAILURE';

// FETCH DATA
export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';


// POST DATA
export const POST_DATA_START = 'POST_DATA_START';
export const POST_DATA_SUCCESS = 'POST_DATA_SUCCESS';
export const POST_DATA_FAILURE = 'POST_DATA_FAILURE';